version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb+srv://22it078:XfEHSwJkbD1Yl5dQ@cluster0.7iaoz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - app-network

  db:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
